#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Tue Dec 17 18:20:58 KST 2024
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 3db750882a5446b882088f9636420e88 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L uvm -L unisims_ver -L unimacro_ver -L secureip --snapshot UVM_FloatingPoint_behav xil_defaultlib.UVM_FloatingPoint xil_defaultlib.glbl -log elaborate.log -L uvm"
xelab -wto 3db750882a5446b882088f9636420e88 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L uvm -L unisims_ver -L unimacro_ver -L secureip --snapshot UVM_FloatingPoint_behav xil_defaultlib.UVM_FloatingPoint xil_defaultlib.glbl -log elaborate.log -L uvm

