# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "D:/GitHub/harman_Verilog/1122_FIFO_UART/1122_FIFO_UART.runs/synth_1/.Xil/Vivado-13004-DESKTOP-7CFQ9ND/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7a35tcpg236-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include d:/GitHub/harman_Verilog/1122_FIFO_UART/1122_FIFO_UART.gen/sources_1/ip/ila_0/hdl/verilog {
      C:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      C:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include d:/GitHub/harman_Verilog/1122_FIFO_UART/1122_FIFO_UART.gen/sources_1/ip/ila_0/hdl/verilog {
      D:/GitHub/harman_Verilog/1122_FIFO_UART/1122_FIFO_UART.srcs/sources_1/imports/harman_Verilog/1121_fifo/1121_fifo.srcs/sources_1/new/fifo.v
      D:/GitHub/harman_Verilog/1122_FIFO_UART/1122_FIFO_UART.srcs/sources_1/imports/harman_Verilog/1115_uart_study/1115_uart_study.srcs/sources_1/new/uart.v
      D:/GitHub/harman_Verilog/1122_FIFO_UART/1122_FIFO_UART.srcs/sources_1/new/uart_fifo_loopback.v
    }
      rt::read_verilog -include d:/GitHub/harman_Verilog/1122_FIFO_UART/1122_FIFO_UART.gen/sources_1/ip/ila_0/hdl/verilog {
      d:/GitHub/harman_Verilog/1122_FIFO_UART/1122_FIFO_UART.gen/sources_1/ip/ila_0/hdl/ltlib_v1_0_vl_rfs.v
      d:/GitHub/harman_Verilog/1122_FIFO_UART/1122_FIFO_UART.gen/sources_1/ip/ila_0/hdl/xsdbs_v1_0_vl_rfs.v
      d:/GitHub/harman_Verilog/1122_FIFO_UART/1122_FIFO_UART.gen/sources_1/ip/ila_0/hdl/xsdbm_v3_0_vl_rfs.v
      d:/GitHub/harman_Verilog/1122_FIFO_UART/1122_FIFO_UART.gen/sources_1/ip/ila_0/hdl/ila_v6_2_syn_rfs.v
      d:/GitHub/harman_Verilog/1122_FIFO_UART/1122_FIFO_UART.gen/sources_1/ip/ila_0/synth/ila_0.v
    }
      rt::read_vhdl -lib blk_mem_gen_v8_3_6 d:/GitHub/harman_Verilog/1122_FIFO_UART/1122_FIFO_UART.gen/sources_1/ip/ila_0/hdl/blk_mem_gen_v8_3_vhsyn_rfs.vhd
      rt::read_vhdl -lib fifo_generator_v13_1_4 d:/GitHub/harman_Verilog/1122_FIFO_UART/1122_FIFO_UART.gen/sources_1/ip/ila_0/hdl/fifo_generator_v13_1_vhsyn_rfs.vhd
      rt::read_vhdl -lib blk_mem_gen_v8_4_4 d:/GitHub/harman_Verilog/1122_FIFO_UART/1122_FIFO_UART.gen/sources_1/ip/ila_0/hdl/blk_mem_gen_v8_4_vhsyn_rfs.vhd
      rt::read_vhdl -lib xpm C:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList D:/GitHub/harman_Verilog/1122_FIFO_UART/1122_FIFO_UART.runs/synth_1/.Xil/Vivado-13004-DESKTOP-7CFQ9ND/realtime/uart_fifo_loopback_synth.xdc
    rt::sdcChecksum
    set rt::top uart_fifo_loopback
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {D:/GitHub/harman_Verilog/1122_FIFO_UART/1122_FIFO_UART.cache/wt}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "D:/GitHub/harman_Verilog/1122_FIFO_UART/1122_FIFO_UART.runs/synth_1/.Xil/Vivado-13004-DESKTOP-7CFQ9ND/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
