webtalk_init -webtalk_dir D:/GitHub/verilog/Verilog/TeamProject_StereoDepth/TeamProject_StereoDepth.sim/sim_1/behav/xsim/xsim.dir/top_VGA_CAMERA_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Dec 31 09:48:42 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "44136bca-741c-479f-80bc-201c867c94ad" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "713703e547394d53a0c8e8d205cab570" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "12th Gen Intel(R) Core(TM) i7-1260P" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2496 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key SystemVerilog -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key File_Counter -value "14" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "1090 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "35 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "304" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "22" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "0.66_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "161620_KB" -context "xsim\\usage"
webtalk_transmit -clientid 354582222 -regid "" -xml D:/GitHub/verilog/Verilog/TeamProject_StereoDepth/TeamProject_StereoDepth.sim/sim_1/behav/xsim/xsim.dir/top_VGA_CAMERA_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/GitHub/verilog/Verilog/TeamProject_StereoDepth/TeamProject_StereoDepth.sim/sim_1/behav/xsim/xsim.dir/top_VGA_CAMERA_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/GitHub/verilog/Verilog/TeamProject_StereoDepth/TeamProject_StereoDepth.sim/sim_1/behav/xsim/xsim.dir/top_VGA_CAMERA_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
